// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A luxurious villa with stunning views and modern amenities.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Luxury Villa",
                            Occupancy = 8,
                            Price = 350.75,
                            Sqft = 5000
                        },
                        new
                        {
                            Id = 2,
                            Description = "A small, cozy cottage perfect for a weekend getaway.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Cozy Cottage",
                            Occupancy = 4,
                            Price = 120.0,
                            Sqft = 1200
                        },
                        new
                        {
                            Id = 3,
                            Description = "A villa located directly on the beach with private access to the sea.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Beachfront Villa",
                            Occupancy = 6,
                            Price = 500.0,
                            Sqft = 4000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
